export const ActionTypes = {
    GET_NUMBER_CART: 'GET_NUMBER_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    FETCH_PRODUCT_DATA_SUCCESS: 'FETCH_PRODUCT_DATA_SUCCESS',
    FETCH_PRODUCT_DATA_FAILURE: 'FETCH_PRODUCT_DATA_FAILURE',
    REMOVE_FROM_CART :"REMOVE_FROM_CART",
    ADD_TO_WISHLIST : 'ADD_TO_WISHLIST',
    REMOVE_FROM_WISHLIST :'REMOVE_FROM_WISHLIST',
    UPDATE_CART_ITEM_QUANTITY:'UPDATE_CART_ITEM_QUANTITY',

}