export const ActionTypes = {
    GET_NUMBER_CART: 'GET_NUMBER_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    FETCH_PRODUCT_DATA_SUCCESS: 'FETCH_PRODUCT_DATA_SUCCESS',
    FETCH_PRODUCT_DATA_FAILURE: 'FETCH_PRODUCT_DATA_FAILURE'

}